app:
  name: "djblog"
  mode: "dev"
  port: ":9090"
  start_time: "2024-02-20"
  machine_id: 1
log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  password: "123456"
  dbname: "djblog"



